from sqlalchemy import Column, Integer, String, DECIMAL, Boolean, SmallInteger, TIMESTAMP
from .Base import Base



class HackatonClientData(Base):
    __tablename__ = 'hackaton_client_data'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)

class Sorted_D2(Base):
    __tablename__ = 'sorted_d2'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)
    relevant_score=Column(Integer, nullable=True)

class Sorted_Expobank(Base):
    __tablename__ = 'sorted_expobank'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)
    relevant_score=Column(Integer, nullable=True)

class Sorted_Expocar(Base):
    __tablename__ = 'sorted_expocar'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)
    relevant_score=Column(Integer, nullable=True)

class Sorted_Hvoya(Base):
    __tablename__ = 'sorted_hvoya'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)
    relevant_score=Column(Integer, nullable=True)

class Sorted_Leasing(Base):
    __tablename__ = 'sorted_leasing'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)
    relevant_score=Column(Integer, nullable=True)
    

class Sorted_Autoexpress(Base):
    __tablename__ = 'sorted_autoexpress'

    id = Column(Integer, primary_key=True, autoincrement=True)
    client_name = Column(String(255), nullable=True)
    client_middle_name = Column(String(255), nullable=True)
    client_sirname = Column(String(255), nullable=True)
    client_birthdate = Column(TIMESTAMP, nullable=True)
    client_birthplace = Column(String(255), nullable=True)
    client_mobile_phone = Column(String(255), nullable=True)
    product = Column(String(100), nullable=True)
    tariff = Column(String(255), nullable=True)
    autosalon = Column(String(255), nullable=True)
    client_education = Column(String(255), nullable=True)
    client_passport_series = Column(String(20), nullable=True)
    client_passport_number = Column(String(20), nullable=True)
    client_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_passport_issue_place = Column(String(200), nullable=True)
    client_passport_issue_code = Column(String(50), nullable=True)
    client_passport_no_previous = Column(Boolean, nullable=True)
    client_zagran_passport_series = Column(String(20), nullable=True)
    client_zagran_passport_number = Column(String(20), nullable=True)
    client_zagran_passport_issue_date = Column(TIMESTAMP, nullable=True)
    client_zagran_passport_issue_place = Column(String(200), nullable=True)
    client_zagran_passport_issue_code = Column(String(50), nullable=True)
    client_driver_license_series = Column(String(255), nullable=True)
    client_driver_license_number = Column(String(255), nullable=True)
    client_driver_license_issue_date = Column(TIMESTAMP, nullable=True)
    client_driver_license_issue_place = Column(String(255), nullable=True)
    client_driver_license_issue_code = Column(String(255), nullable=True)
    credit_sum = Column(DECIMAL(12, 2), nullable=True)
    credit_term = Column(SmallInteger, nullable=True)
    credit_initial = Column(DECIMAL(12, 2), nullable=True)
    credit_dog_issue_date = Column(TIMESTAMP, nullable=True)
    client_family_status = Column(String(255), nullable=True)
    client_children_dependents = Column(SmallInteger, nullable=True)
    client_registration_address = Column(String(255), nullable=True)
    client_registration_own_type = Column(String(255), nullable=True)
    client_registration_date = Column(TIMESTAMP, nullable=True)
    job_type = Column(String(255), nullable=True)
    workplace_name = Column(String(255), nullable=True)
    workplace_inn = Column(String(255), nullable=True)
    workplace_client_position = Column(String(255), nullable=True)
    workplace_address = Column(String(255), nullable=True)
    workplace_phone = Column(String(255), nullable=True)
    workplace_workdate = Column(TIMESTAMP, nullable=True)
    workplace_work_experience = Column(SmallInteger, nullable=True)
    workplace_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_amount = Column(DECIMAL(12, 2), nullable=True)
    workplace_additional_income_type = Column(String(255), nullable=True)
    car_brand = Column(String(255), nullable=True)
    car_model = Column(String(255), nullable=True)
    car_year = Column(String(255), nullable=True)
    car_price = Column(DECIMAL(10, 2), nullable=True)
    car_dop_price = Column(DECIMAL(10, 2), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_condition = Column(String(255), nullable=True)
    car_transmission = Column(String(255), nullable=True)
    car_mileage = Column(String(255), nullable=True)
    client_email = Column(String(255), nullable=True)
    client_company= Column(String(255), nullable=True)
    relevant_score=Column(Integer, nullable=True)